{
 "title": "A4",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Relative Request Latency per Version",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(version) (rate(frontend_prediction_latency_seconds_sum[$__rate_interval])) / (sum by(version) (rate(frontend_prediction_latency_seconds_count[$__rate_interval])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Avg Latency per Version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum by(version) (rate(frontend_prediction_latency_seconds_sum[$__rate_interval])) / (sum by(version) (rate(frontend_prediction_latency_seconds_count[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Average CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(backend_cpu_usage_percent[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hits on model-service v2",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(backend_cache_hits[$__rate_interval])) / sum(increase(backend_total_requests[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "System Average Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(backend_memory_used_bytes) / (avg(backend_memory_max_bytes))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}