{
 "title": "App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(version) (avg_over_time(jvm_memory_used_bytes{area=\"heap\", version=\"v1\"}[$__interval])) / (sum by(version) (avg_over_time(jvm_memory_max_bytes{area=\"heap\"}[$__interval])))",
     "legendFormat": "app {{version}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_usage{version=\"v1\"}[$__interval])",
     "legendFormat": "{{container}} {{version}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Endpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{outcome=\"SUCCESS\"}[$__rate_interval]) / rate(http_server_requests_seconds_count{outcome=\"SUCCESS\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Model-Service Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"POST\", uri=\"/sms/\"}[$__rate_interval]) / rate(http_server_requests_seconds_count{method=\"POST\", uri=\"/sms/\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(result) (rate(frontend_sms_requests_total[$__rate_interval]))",
     "legendFormat": "app"
    }
   ]
  },
  {
   "title": "Server Request Overall Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 17 },
   "targets": [
    {
     "expr": "frontend_prediction_latency_seconds_bucket",
     "legendFormat": "Less Than"
    }
   ]
  }
 ]
}